#!/bin/bash
#
#
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

# jvm
export MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled"


# virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# dotfiles
EXCLUDES="README.md LICENSE"
DOTFILES_DIRS="$HOME/dotfiles-local $HOME/dotfiles"


# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"


# gvm
source $HOME/.gvm/scripts/gvm

## go
export GOPATH=$HOME/gowork
export PATH=$PATH:$GOPATH/bin

# aws
export AWS_DEFAULT_PROFILE=aws_ro

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
